# Use postgres/example user/password credentials

services:

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./dbdata:/var/lib/postgresql/data # Persist data between restarts
    networks:
      - activitybox

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - activitybox

networks:
  activitybox:
