onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - 'esbuild'
  - 'nx'
  - 'prisma'

catalogs:
  prisma:
    prisma: latest

packages:
  - "apps/*"
  - "libs/*"